#!/bin/bash

################################################################/
## author    Chris L Baker (clb) <clbaker@rec.ri.cmu.edu>
## date      2013.09.06
## brief     Simplify the interface to pushbullet
##
## attention Copyright (C) 2013
## attention Chris L Baker (clb)
## attention All rights reserved
################################################################/

# The version
function version()
{
    echo
    echo "VERSION"
    echo "        push is version 0.0.1"
    echo
    echo "AUTHOR"
    echo "        Chris L Baker (clb) <clbaker@rec.ri.cmu.edu>"
    echo
    echo "COPYRIGHT"
    echo "        Copyright (C) 2013"
    echo "        Chris L Baker (clb)"
    echo "        All rights reserved"
    echo
}

# The usage
function usage()
{
    echo
    echo "NAME"
    echo "        push - Push something to a phone using pushbullet"
    echo
    echo "SYNOPSIS"
    echo "        push [OPTIONS]"
    echo
    echo "        Supply a subject and a message and it will be pushed to your phone"
    echo "        The file ~./config/pushbullet/pushrc is used for the phone's key and id"
    echo
    echo "DESCIRPTION"
    echo "        -u=url (default=https://www.pushbullet.com/api/pushes)"
    echo "            The url to pushbullet"
    echo
    echo "        -k=userkey"
    echo "            The user key from push bullet"
    echo
    echo "        -d=device"
    echo "            The device to push to"
    echo
    echo "        -t=type (default=note)"
    echo "            The message (pushbullet support several types)"
    echo
    echo "        -s=subject"
    echo "            The subject of the message"
    echo
    echo "        -b=body"
    echo "            The body of the message"
    echo
    echo "        -v,--version"
    echo "            Print version information and exit"
    echo
    echo "        -h,--help"
    echo "            Print the help and usage (this information) and exit"
    echo
    echo "FILES"
    echo "        The only optional file used by this scrip is located in ~/.config/pushbullet/pushrc."
    echo "        If this file exists, it is sourced verbatim and so default parameters can be set therein."
    echo "        Typically only the userkey and device need to be specified, but any command line option"
    echo "        may be set. The options on the command line will override the options in the config file"
    echo "        if they are specified."
    echo
    echo "        Here is a sample pushrc file"
    echo
    echo "        -------------------------------------------------------------------------------"
    echo "        # configuration for pushrc"
    echo
    echo "        # define my user key as specified on pushbullet"
    echo "        userkey=eafdbaa921da2f31aabc662a2451bdd1:"
    echo
    echo "        # define my device id as specified on pushbullet"
    echo "        device=23312"
    echo
    echo "        # I like having a default subject line so I don't have to type it all the time"
    echo "        subject=\"You are awesome\""
    echo "        -------------------------------------------------------------------------------"
    version
}

# we require curl
if [[ -z `which curl` ]]; then
    echo " *** ERROR: you must have curl installed - try 'sudo apt-get install curl'"
    exit -1
fi

# defaults
type="note"
url="https://www.pushbullet.com/api/pushes"

# source config file here so it can be overriden by command line options
configFile="$HOME/.config/pushbullet/pushrc"
if [[ -f $configFile ]]; then
    source "$configFile"
fi

# use this to get the command line options
command="::> $0 $(getopt -l \"version,help\" \"u:k:d:t:s:b:vh\" \"$@\" 2>&1 > /dev/null)"

# process the command line
while [ $# -gt 0 ]; do
    case "$1" in
        (-u) url="$2"; shift;;
        (-k) userkey="$2"; shift;;
        (-d) device="$2"; shift;;
        (-t) type="$2"; shift;;
        (-s) subject="$2"; shift;;
        (-b) body="$2"; shift;;
        (-v|--version) version; exit 0;;
        (-h|--help) usage; exit 0;;
        (--) shift; break;;
        (*|-*|--*)
        echo
        echo "Command Provided $command" 1>&2
        echo " --> ERROR - unrecognized option '$1'" 1>&2
        echo " --> try -h for usage help" 1>&2
        echo
        exit -1
        ;;
    esac
    shift
done

# check inputs
if [[ -z $url ]]; then
    echo " *** ERROR: you must specify a url (-h for help)"
    exit -1
fi

if [[ -z $userkey ]]; then
    echo " *** ERROR: you must specify a userkey (-h for help)"
    exit -1
fi

if [[ -z $device ]]; then
    echo " *** ERROR: you must specify a device (-h for help)"
    exit -1
fi

if [[ -z $subject ]]; then
    echo " *** ERROR: you must specify a subject (-h for help)"
    exit -1
fi

if [[ -z $body ]]; then
    echo " *** ERROR: you must specify a body (-h for help)"
    exit -1
fi

curl "$url" \
    -u "$userkey:" \
    -d device_id="$device" \
    -d type="$type" \
    -d title="$subject" \
    -d body="$body" \
    -X POST > /dev/null 2>&1
